credentials:
  usernames:
    admin:
      email: 'harsh.vaidya@insansa.com'
      name: 'harsh'
      password: 'harsh123' # hashed password of 'abc'
      # to generate hashed password use below code.
      # hashed_passwords = stauth.Hasher(['abc']).generate()

cookie:
  expiry_days: 30
  key: 'some_signature_key' # Must be string
  name: 'some_cookie_name'
preauthorized:
  emails:
  - 'harsh.vaidya@insansa.com'